import type { ConfigProviderThemeVars } from '@wot-ui/ui/components/wd-config-provider/types'
import type { ThemeTokens } from './tokens'

export function toWotThemeVars(tokens: ThemeTokens): Partial<ConfigProviderThemeVars> {
  return {
    navbarBg: tokens.bgCard,
    navbarColor: tokens.navbarTextColor,
    navbarDescColor: tokens.textSecondary,
    navbarTitleFontSize: tokens.navbarTitleFontSize,
    navbarTitleFontWeight: tokens.navbarTitleFontWeight,
    primary5: tokens.primary,
    primary6: tokens.primary,
    successMain: tokens.success,
    warningMain: tokens.warning,
    dangerMain: tokens.danger,
    textMain: tokens.textPrimary,
    textSecondary: tokens.textSecondary,
    borderMain: tokens.borderPrimary,
    filledBottom: tokens.bgCard,
    filledContent: tokens.bgSurfaceMuted,
    filledOppo: tokens.textInverse,
    tabbarBg: tokens.tabbarBg,
    tabbarItemColorActive: tokens.primary,
    tabbarItemColorInactive: tokens.textMuted
  }
}

export function toCssVars(tokens: ThemeTokens): Record<string, string> {
  return {
    '--app-color-primary': tokens.primary,
    '--app-color-primary-soft': tokens.primarySoft,
    '--app-color-success': tokens.success,
    '--app-color-success-soft': tokens.successSoft,
    '--app-color-warning': tokens.warning,
    '--app-color-warning-soft': tokens.warningSoft,
    '--app-color-danger': tokens.danger,
    '--app-color-danger-soft': tokens.dangerSoft,
    '--app-color-info': tokens.info,
    '--app-color-info-soft': tokens.infoSoft,
    '--app-text-primary': tokens.textPrimary,
    '--app-text-secondary': tokens.textSecondary,
    '--app-text-muted': tokens.textMuted,
    '--app-text-inverse': tokens.textInverse,
    '--app-text-placeholder': tokens.textPlaceholder,
    '--app-text-disabled': tokens.textDisabled,
    '--app-text-brand': tokens.textBrand,
    '--app-bg-page': tokens.bgPage,
    '--app-bg-page-secondary': tokens.bgPageSecondary,
    '--app-bg-card': tokens.bgCard,
    '--app-bg-elevated': tokens.bgElevated,
    '--app-bg-surface-muted': tokens.bgSurfaceMuted,
    '--app-bg-interactive': tokens.bgInteractive,
    '--app-bg-float': tokens.bgFloat,
    '--app-border-primary': tokens.borderPrimary,
    '--app-border-secondary': tokens.borderSecondary,
    '--app-border-inverse': tokens.borderInverse,
    '--app-divider': tokens.divider,
    '--app-shadow-card': tokens.shadowCard,
    '--app-shadow-float': tokens.shadowFloat,
    '--app-tabbar-bg': tokens.tabbarBg,
    '--app-tabbar-floating-bg': tokens.tabbarFloatingBg,
    '--app-tabbar-border': tokens.tabbarBorder,
    '--app-tabbar-shadow': tokens.tabbarShadow,
    '--app-input-bg': tokens.inputBg,
    '--app-input-text': tokens.inputText,
    '--app-input-border': tokens.inputBorder,
    '--app-input-placeholder': tokens.inputPlaceholder,
    '--app-button-primary-bg': tokens.buttonPrimaryBg,
    '--app-button-primary-text': tokens.buttonPrimaryText,
    '--app-button-primary-disabled-bg': tokens.buttonPrimaryDisabledBg,
    '--app-button-secondary-bg': tokens.buttonSecondaryBg,
    '--app-button-secondary-text': tokens.buttonSecondaryText,
    '--app-overlay-dark': tokens.overlayDark,
    '--app-overlay-border': tokens.overlayBorder,
    '--app-overlay-icon': tokens.overlayIcon,
    '--app-status-pending': tokens.statusPending,
    '--app-status-shipped': tokens.statusShipped,
    '--app-status-completed': tokens.statusCompleted,
    '--app-gradient-primary': tokens.gradientPrimary,
    '--app-gradient-info': tokens.gradientInfo,
    '--app-gradient-user-header': tokens.gradientUserHeader,
    '--wot-navbar-title-font-size': tokens.navbarTitleFontSize,
    '--wot-navbar-color': tokens.navbarTextColor,
    '--wot-navbar-title-font-weight': tokens.navbarTitleFontWeight
  }
}
